### ISSUE TITLE
Padding at bottom of the card

### ISSUE THREAD

**Issue by masminl** [argaar/comfortable-environment-card#19]
I love how this card visualizes the comfort level and want to make it part of my dashboard!
Did notice that the padding on the bottom is a little off. Can the padding be fixed so it's consistent with the top/sides?
<img width="437" alt="Scherm­afbeelding 2024-01-20 om 08 40 09" src="https://github.com/argaar/comfortable-environment-card/assets/28845289/978db447-dd15-40e2-99d3-e6310fc04a9e">

**Comment by argaar** [comment]
Hi @masminl unfortunately I can't reproduce the issue, but I've tried some small adjustments
Could you try the pre release 1.5.6-rc0 that I've just released and let me know if it fixes the glitch?

**Comment by masminl** [comment]
@argaar thanks for looking into this, unfortunately the issue persists. I tried using a different theme on both IOS app and Chrome all the same result. Is there anything I can do to help you reproduce?

**Comment by argaar** [comment]
@masminl which theme are you using? I can try install it and see if it's bugged on my side

**Comment by masminl** [comment]
Hi Davide,
I’m using this theme
https://github.com/basnijholt/lovelace-ios-themes

Greetings,
Samuel

Op wo 24 jan 2024 om 12:23 schreef Davide Foschi ***@***.***>

**Comment by argaar** [comment]
@masminl Just published 1.5.6-rc1 that should fix the issue, I've installed the theme and tested on my own environment and it seems to be ok.
Very nice theme btw

**Comment by masminl** [comment]
Indeed the theme is a great one!
I just installed rc1 and the issue is fixed.
Thanks so much for looking into this and fixing so quickly. That’s what
makes Home Assistant the best platform.

Op wo 24 jan 2024 om 14:44 schreef Davide Foschi ***@***.***>
